generate ct0 エイト

diff --git a/.github/workflows/X.yml b/.github/workflows/X.yml
--- a/.github/workflows/X.yml
+++ b/.github/workflows/X.yml
@@ -30,11 +30,10 @@ jobs:
           -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36' \
           -H 'x-csrf-token: ${{ steps.gen_ct0.outputs.ct0 }}' \
           --data-raw '{"variables":{"tweet_text":"${{ github.event.issue.title }}","dark_request":false,"media":{"media_entities":[],"possibly_sensitive":false},"semantic_annotation_ids":[],"disallowed_reply_options":null},"features":{"premium_content_api_read_enabled":false,"communities_web_enable_tweet_community_results_fetch":true,"c9s_tweet_anatomy_moderator_badge_enabled":true,"responsive_web_grok_analyze_button_fetch_trends_enabled":false,"responsive_web_grok_analyze_post_followups_enabled":true,"responsive_web_jetfuel_frame":false,"responsive_web_grok_share_attachment_enabled":true,"responsive_web_edit_tweet_api_enabled":true,"graphql_is_translatable_rweb_tweet_is_translatable_enabled":true,"view_counts_everywhere_api_enabled":true,"longform_notetweets_consumption_enabled":true,"responsive_web_twitter_article_tweet_consumption_enabled":true,"tweet_awards_web_tipping_enabled":false,"responsive_web_grok_show_grok_translated_post":false,"responsive_web_grok_analysis_button_from_backend":true,"creator_subscriptions_quote_tweet_preview_enabled":false,"longform_notetweets_rich_text_read_enabled":true,"longform_notetweets_inline_media_enabled":true,"profile_label_improvements_pcf_label_in_post_enabled":true,"rweb_tipjar_consumption_enabled":true,"responsive_web_graphql_exclude_directive_enabled":true,"verified_phone_label_enabled":false,"articles_preview_enabled":true,"responsive_web_graphql_skip_user_profile_image_extensions_enabled":false,"freedom_of_speech_not_reach_fetch_enabled":true,"standardized_nudges_misinfo":true,"tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled":true,"responsive_web_grok_image_annotation_enabled":true,"responsive_web_graphql_timeline_navigation_enabled":true,"responsive_web_enhance_cards_enabled":false}}'`
-          echo $RESP | jq -e 'has("errors")' && exit 1
+          echo $RESP | jq -e 'has("errors")' && echo $RESP && exit 1
           echo $RESP | echo rest_id=`jq '.data.create_tweet.tweet_results.result.rest_id' | tr -d '"'` >> $GITHUB_OUTPUT
-
       - name: Summary
         if: success()
         run: |
           echo "# https://x.com/Ryoga_exe/status/${{ steps.tweet.outputs.rest_id }}" >> $GITHUB_STEP_SUMMARY
-          echo "「${{ github.event.issue.title }}」は${{ github.event.issue.user.login }}によって$(TZ='Asia/Tokyo' date)に作成されました！" >> $GITHUB_STEP_SUMMARY
+          echo "「${{ github.event.issue.title }}」は${{ github.event.issue.user.login }}によって$(TZ='Asia/Tokyo' date)に投稿されました" >> $GITHUB_STEP_SUMMARY
